
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/billing_app}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0

aws.access.key=${AWS_ACCESS_KEY:}
aws.secret.key=${AWS_SECRET_KEY:}
aws.region=${AWS_REGION:ap-southeast-2}
aws.bucket.name=${AWS_BUCKET_NAME:}

jwt.secret.key=${JWT_SECRET_KEY:change-me-in-env}

razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}